# Generated by Django 5.0.3 on 2024-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idObra', models.FloatField()),
                ('idUsuario', models.IntegerField()),
                ('nombreObra', models.TextField()),
                ('georeferencia', models.ImageField(upload_to='')),
                ('estadoObra', models.TextField()),
                ('fechaInicioObra', models.DateTimeField()),
                ('archivos', models.FileField(upload_to='')),
            ],
        ),
    ]
