# Generated by Django 5.0.3 on 2024-06-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obra',
            table='obra',
        ),
    ]
