# Generated by Django 5.0.3 on 2024-06-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_obra_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estadoObra',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='obra',
            name='idObra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombreObra',
            field=models.CharField(max_length=30),
        ),
    ]
