# Generated by Django 5.0.3 on 2024-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_obra_estadoobra_alter_obra_idobra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fechaInicioObra',
            field=models.DateField(),
        ),
    ]
