# Generated by Django 5.0.3 on 2024-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_obra_fechainicioobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='georeferencia',
            field=models.FileField(upload_to=''),
        ),
    ]
